rename b.jpg b.jpg
rename bayport_logo.jpg bayport_logo.jpg
rename bpbc.png bpbc.png
rename cmmidev3_logo.png cmmidev3_logo.png
rename dialogo_logo.png dialogo_logo.png
rename DLG-AVION-AZUL.png dlg-avion-azul.png
rename DLG-BARRA-Ahorros.png dlg-barra-ahorros.png
rename DLG-BARRA-Cartera.png dlg-barra-cartera.png
rename DLG-BARRA-Clave.png dlg-barra-clave.png
rename DLG-BARRA-Clientes.png dlg-barra-clientes.png
rename DLG-BARRA-Comisiones.png dlg-barra-comisiones.png
rename DLG-BARRA-Conciliacion.png dlg-barra-conciliacion.png
rename DLG-BARRA-CXC-CXP.png dlg-barra-cxc-cxp.png
rename DLG-BARRA-Firma.png dlg-barra-firma.png
rename DLG-BARRA-Libranzas.png dlg-barra-libranzas.png
rename DLG-BARRA-LIQ-COMISIONES.png dlg-barra-liq-comisiones.png
rename DLG-BARRA-MIT.png dlg-barra-mit.png
rename DLG-BARRA-Parametros.png dlg-barra-parametros.png
rename DLG-BARRA-POLIZAS-SEGURO.png dlg-barra-polizas-seguro.png
rename DLG-BARRA-PQRS.png dlg-barra-pqrs.png
rename DLG-BARRA-Salir.png dlg-barra-salir.png
rename DLG-BARRA-Seguridad.png dlg-barra-seguridad.png
rename DLG-BARRA-Tesoreria.png dlg-barra-tesoreria.png
rename DLG-CARPETA-AZUL.png dlg-carpeta-azul.png
rename DLG-CARPETA-AZUL2.jpg dlg-carpeta-azul2.jpg
rename DLG-CORREO-REDONDO-AZUL.png dlg-correo-redondo-azul.png
rename DLG-CRONOMETRO-AZUL.png dlg-cronometro-azul.png
rename DLG-CURSOR-AZUL.png dlg-cursor-azul.png
rename DLG-ESCANER-AZUL.png dlg-escaner-azul.png
rename DLG-FOLDER-AZUL.png dlg-folder-azul.png
rename DLG-LISTA-AZUL.png dlg-lista-azul.png
rename DLG-LLAVE-AZUL.png dlg-llave-azul.png
rename DLG-PORTAL-AGENTES.png dlg-portal-agentes.png
rename DLG-RELOAD-AZUL.png dlg-reload-azul.png
rename DLG-TELEFONO-ARROBA.png dlg-telefono-arroba.png
rename fortalezaIcon.png fortalezaicon.png
rename ico_preload.gif ico_preload.gif
rename loader1.gif loader1.gif
rename logo.jpg logo.jpg
rename logob.jpg logob.jpg
rename logotw.jpg logotw.jpg
rename Logo_final_bayport_only.png logo_final_bayport_only.png
rename mi.png mi.png
rename modulo.png modulo.png
rename nav-expand.png nav-expand.png
rename quienes_somos.jpg quienes_somos.jpg
rename tecnoevolucion_logo.png tecnoevolucion_logo.png
rename ticon.png ticon.png
  