export class TECBOG_RolesModel {
    public compania: number = 1;
    public tecbogRolesaplicacionCodigo: number = 0.0;
    public tecbogRolesCodigoRol: number = 0.0;
    public tecboG_Roles_Comp: string;
    public tecbogRolesRolNombre: string;
    public tecbogRolesRolEstado: number;
    public tecbogRolesAutorizaPlanilla: boolean;
    public tecbogRolesFuncAutorizado: boolean;
    public tecbogRolesSwAnulacion: boolean;
    public tecbogRolesAutorizacionIngreso: boolean;
    public tecbogRolesBloqueoIngreso: boolean;
    public tecbogRolesCrearCliente: boolean;
    public tecbogRolesHoraBloqueo: number;
    public tecbogRolesMinutoBloqueo: number;
    public tecbogRolesAdmonPortafolio: boolean;
    public tecbogRolesSimulacion: boolean;
    public tecbogRolesExtracto: boolean;
    public tecbogRolesCrearInver: boolean;
    public tecbogRolesCambioEmpresa: boolean;
    public tecbogRolesPuedeFuturos: boolean;
    public tecbogRolesAutorizacionAdmon: boolean;
    public tecbogRolesValorEfectivo: number = 0.0;
    public tecbogRolesSaldoCajero: number = 0.0;
    public tecbogRolesCambioContrib: number = 0.0;
    public tecbogRolesTiempoEspera: Date;
    public tecbogRolesUsrInter: boolean;
    public tecbogRolesAdmonInforme: boolean;
    public tecbogRolesHoraIngreso: Date;
    public tecbogRolesTipoSeguridad: number;
    public tecbogRolesModiComprobante: boolean;
    public tecbogRolesRetFechCompro: boolean;
    public tecbogRolesTipoHsystem: string;
    public tecbogRolesDv11Menu: boolean;
    public tecbogRolesAplicacion1: boolean;
    public tecbogRolesAplicacion2: boolean;
    public tecbogRolesAplicacion3: boolean;
    public tecbogRolesAplicacion4: boolean;
    public tecbogRolesAplicacion5: boolean;
    public tecbogRolesAplicacion6: boolean;
    public tecbogRolesAplicacion7: boolean;
    public tecbogRolesPantalla: string;
    public tecbogRolesBloqueoMovto: boolean;
    public tecbogRolesConsultaSaldo: boolean;
    public tecbogRolesIndEjecutivo: boolean;
    public tecbogRolesTipoFirma: string;
    public tecbogRolesCambioContabilidad: boolean;
    public tecbogRolesSaldoMe: number = 0.0;
    public tecbogRolesEditaIdbAutomatico: boolean;
    public tecbogRolesGeneraBitacora: boolean;
    public tecbogRolesModificaParImptos: boolean;
    public tecbogRolesModificaClientes: boolean;
    public tecbogRolesAdministradorUsuarios: boolean;
    public tecbogRolesCambioEdoPagoProv: boolean;
    public tecbogRolesNivelCartera: number = 0.0;
    public tecbogRolesNivelDpf: number = 0.0;
    public tecbogRolesAdministraPuc: boolean;
    public tecbogRolesAplicativo: boolean;
    public tecbogRolesCrearUsuarios: boolean;
    public tecbogRolesModiFecProgramda: boolean;
    public tecbogRolesAsignaTitulo: boolean;
    public tecbogRolesCambioSucTesoreria: boolean;
    public tecbogRolesIndChequeras: boolean;
    public tecbogRolesConsultaClientes: boolean;
    public tecbogRolesParametrosCaja: boolean;
    public tecbogRolesTransaccionesCaja: boolean;
    public tecbogRolesEfecOperaTeso: boolean;
    public tecbogRolesNroModificaciones: number = 0.0;
    public tecbogRolesSwEjecutaDepurador: boolean;
    public tecbogRolesSwCodigosDepurador: boolean;
    public tecbogRolesSwModifCuentas: boolean;
    public tecbogRolesSwUsuarioDwh: boolean;
    public tecbogRolesCambioSucAhorro: boolean;
    public tecbogRolesCorreoElectronico: boolean;
    public tecbogRolesNumeroCelular: boolean;
    public tecbogRolesIndIngresoLibranza: number = 0.0;
    public tecbogRolesPerfilLibranza: number = 0.0;
    public tecbogRolesPerfilTableros: number = 0.0;
    public tecbogRolesIndModifParAhoSuc: boolean;
    public tecbogRolesIndAutorizaCondManejo: boolean;
    public tecbogRolesIndEliminaCondManejo: boolean;
    public tecbogRolesIndModificaCondManejo: boolean;
    public tecbogRolesIndParManejoFirmasSuc: boolean;
    public tecbogRolesIndModFirmas: boolean;
    public tecbogRolesIndAutFirmas: boolean;
    public tecbogRolesIndInsertFirmas: boolean;
    public tecbogRolesPerfilProvisionAtm: boolean;
    public tecbogRolesCodigoEmpleado: string;
    public tecbogRolesCodZona: number = 0.0;
    public tecbogRolesTipoAsesor: number = 0.0;
    public tecbogRolesAplicaIncentivos: boolean;
    public tecbogRolesTipoFirmaTeso: string;
    public tecbogRolesFechaModDato: Date;
    public tecbogRolesUsuarioModDat: string;
    public tecbogRolesFechaModClave: Date;
    public tecbogRolesModalidadAsesor: number = 0.0;
    public tecbogRolesCdtsTesoreria: boolean;
    public tecbogRolesIndSeguimientoUsuarios: boolean;
    public tecbogRolesNoAutorImpresiones: boolean;
    public tecbogRolesPerfilPqr: number = 0.0;
    public tecbogRolesProfileBaseDatos: string;
    public tecbogRolesRolBaseDatos: string;
    public tecbogRolesIndAdministrarUsuarios: number = 0.0;
    public tecbogRolesIndAdministrarRoles: number = 0.0;
    public tecbogRolesIndCrearUsuarios: number = 0.0;
    public tecbogRolesIndCrearRoles: number = 0.0;
    public tecbogRolesIndAdministrarAlertas: number = 0.0;
    public tecbogRolesIndTipoSegXTECBOGRolesModulo: number = 0.0;
    public tecbogRolesIndGeneraReportesGrales: number = 0.0;
    public tecbogRolesIndGeneraReportesLog: number = 0.0;
    public tecbogRolesMontoMaxOrdengiroCxp: number = 0.0;
    public tecbogRolesFiltroReportesCdts: number = 0.0;
    public tecbogRolesRolBaseDatosCaja: string;
    public tecbogRolesTipoFirmaWfc: string;
    public tecbogRolesNivelInformes: number = 0.0;
    public tecbogRolesIndAnalistaAprobacion: string;
    public tecbogRolesIndCambioZona: number = 0.0;
    public tecbogRolesDiasPassword: number = 0.0;
    public tecbogRolesNivel: number = 0.0;
    public tecbogRolesHorario: number = 0.0;
    public tecbogRolesIndAdministraNominaAho: number = 0.0;
    public tecbogRolesUsuarioOficinaCxcCxp: number = 0.0;
    public tecbogRolesAutorAnulaChq: number = 0.0;
    public tecbogRolesAutReimpChq: number = 0.0;
    public tecbogRolesIndCierre: number = 0.0;
    public tecbogRolesIndAnalistaAprobacionActivo: string;
    public tecbogRolesValorAsignacionInicial: number = 0.0;
    public tecbogRolesValorAsignacionFinal: number = 0.0;
    public secuencia: number;
    public estado: string = 'N';
    public _id: string;
    public _v: number;
    public relaciones: any;

    constructor(json: any = null) {
        this.relaciones = {};
        if (json !== null) {
            this.tecbogRolesaplicacionCodigo = json.tecbogRolesaplicacionCodigo;
            this.tecbogRolesCodigoRol = json.tecbogRolesCodigoRol;
            this.tecboG_Roles_Comp =  json.tecboG_Roles_Comp;
            this.tecbogRolesRolNombre = json.tecbogRolesRolNombre;
            this.tecbogRolesRolEstado = json.tecbogRolesRolEstado;
            this.tecbogRolesAutorizaPlanilla = json.tecbogRolesAutorizaPlanilla;
            this.tecbogRolesFuncAutorizado = json.tecbogRolesFuncAutorizado;
            this.tecbogRolesSwAnulacion = json.tecbogRolesSwAnulacion;
            this.tecbogRolesAutorizacionIngreso = json.tecbogRolesAutorizacionIngreso;
            this.tecbogRolesBloqueoIngreso = json.tecbogRolesBloqueoIngreso;
            this.tecbogRolesCrearCliente = json.tecbogRolesCrearCliente;
            this.tecbogRolesHoraBloqueo = json.tecbogRolesHoraBloqueo;
            this.tecbogRolesMinutoBloqueo = json.tecbogRolesMinutoBloqueo;
            this.tecbogRolesAdmonPortafolio = json.tecbogRolesAdmonPortafolio;
            this.tecbogRolesSimulacion = json.tecbogRolesSimulacion;
            this.tecbogRolesExtracto = json.tecbogRolesExtracto;
            this.tecbogRolesCrearInver = json.tecbogRolesCrearInver;
            this.tecbogRolesCambioEmpresa = json.tecbogRolesCambioEmpresa;
            this.tecbogRolesPuedeFuturos = json.tecbogRolesPuedeFuturos;
            this.tecbogRolesAutorizacionAdmon = json.tecbogRolesAutorizacionAdmon;
            this.tecbogRolesValorEfectivo = json.tecbogRolesValorEfectivo;
            this.tecbogRolesSaldoCajero = json.tecbogRolesSaldoCajero;
            this.tecbogRolesCambioContrib = json.tecbogRolesCambioContrib;
            this.tecbogRolesTiempoEspera = json.tecbogRolesTiempoEspera;
            this.tecbogRolesUsrInter = json.tecbogRolesUsrInter;
            this.tecbogRolesAdmonInforme = json.tecbogRolesAdmonInforme;
            this.tecbogRolesHoraIngreso = json.tecbogRolesHoraIngreso;
            this.tecbogRolesTipoSeguridad = json.tecbogRolesTipoSeguridad;
            this.tecbogRolesModiComprobante = json.tecbogRolesModiComprobante;
            this.tecbogRolesRetFechCompro = json.tecbogRolesRetFechCompro;
            this.tecbogRolesTipoHsystem = json.tecbogRolesTipoHsystem;
            this.tecbogRolesDv11Menu = json.tecbogRolesDv11Menu;
            this.tecbogRolesAplicacion1 = json.tecbogRolesAplicacion1;
            this.tecbogRolesAplicacion2 = json.tecbogRolesAplicacion2;
            this.tecbogRolesAplicacion3 = json.tecbogRolesAplicacion3;
            this.tecbogRolesAplicacion4 = json.tecbogRolesAplicacion4;
            this.tecbogRolesAplicacion5 = json.tecbogRolesAplicacion5;
            this.tecbogRolesAplicacion6 = json.tecbogRolesAplicacion6;
            this.tecbogRolesAplicacion7 = json.tecbogRolesAplicacion7;
            this.tecbogRolesPantalla = json.tecbogRolesPantalla;
            this.tecbogRolesBloqueoMovto = json.tecbogRolesBloqueoMovto;
            this.tecbogRolesConsultaSaldo = json.tecbogRolesConsultaSaldo;
            this.tecbogRolesIndEjecutivo = json.tecbogRolesIndEjecutivo;
            this.tecbogRolesTipoFirma = json.tecbogRolesTipoFirma;
            this.tecbogRolesCambioContabilidad = json.tecbogRolesCambioContabilidad;
            this.tecbogRolesSaldoMe = json.tecbogRolesSaldoMe;
            this.tecbogRolesEditaIdbAutomatico = json.tecbogRolesEditaIdbAutomatico;
            this.tecbogRolesGeneraBitacora = json.tecbogRolesGeneraBitacora;
            this.tecbogRolesModificaParImptos = json.tecbogRolesModificaParImptos;
            this.tecbogRolesModificaClientes = json.tecbogRolesModificaClientes;
            this.tecbogRolesAdministradorUsuarios = json.tecbogRolesAdministradorUsuarios;
            this.tecbogRolesCambioEdoPagoProv = json.tecbogRolesCambioEdoPagoProv;
            this.tecbogRolesNivelCartera = json.tecbogRolesNivelCartera;
            this.tecbogRolesNivelDpf = json.tecbogRolesNivelDpf;
            this.tecbogRolesAdministraPuc = json.tecbogRolesAdministraPuc;
            this.tecbogRolesAplicativo = json.tecbogRolesAplicativo;
            this.tecbogRolesCrearUsuarios = json.tecbogRolesCrearUsuarios;
            this.tecbogRolesModiFecProgramda = json.tecbogRolesModiFecProgramda;
            this.tecbogRolesAsignaTitulo = json.tecbogRolesAsignaTitulo;
            this.tecbogRolesCambioSucTesoreria = json.tecbogRolesCambioSucTesoreria;
            this.tecbogRolesIndChequeras = json.tecbogRolesIndChequeras;
            this.tecbogRolesConsultaClientes = json.tecbogRolesConsultaClientes;
            this.tecbogRolesParametrosCaja = json.tecbogRolesParametrosCaja;
            this.tecbogRolesTransaccionesCaja = json.tecbogRolesTransaccionesCaja;
            this.tecbogRolesEfecOperaTeso = json.tecbogRolesEfecOperaTeso;
            this.tecbogRolesNroModificaciones = json.tecbogRolesNroModificaciones;
            this.tecbogRolesSwEjecutaDepurador = json.tecbogRolesSwEjecutaDepurador;
            this.tecbogRolesSwCodigosDepurador = json.tecbogRolesSwCodigosDepurador;
            this.tecbogRolesSwModifCuentas = json.tecbogRolesSwModifCuentas;
            this.tecbogRolesSwUsuarioDwh = json.tecbogRolesSwUsuarioDwh;
            this.tecbogRolesCambioSucAhorro = json.tecbogRolesCambioSucAhorro;
            this.tecbogRolesCorreoElectronico = json.tecbogRolesCorreoElectronico;
            this.tecbogRolesNumeroCelular = json.tecbogRolesNumeroCelular;
            this.tecbogRolesIndIngresoLibranza = json.tecbogRolesIndIngresoLibranza;
            this.tecbogRolesPerfilLibranza = json.tecbogRolesPerfilLibranza;
            this.tecbogRolesPerfilTableros = json.tecbogRolesPerfilTableros;
            this.tecbogRolesIndModifParAhoSuc = json.tecbogRolesIndModifParAhoSuc;
            this.tecbogRolesIndAutorizaCondManejo = json.tecbogRolesIndAutorizaCondManejo;
            this.tecbogRolesIndEliminaCondManejo = json.tecbogRolesIndEliminaCondManejo;
            this.tecbogRolesIndModificaCondManejo = json.tecbogRolesIndModificaCondManejo;
            this.tecbogRolesIndParManejoFirmasSuc = json.tecbogRolesIndParManejoFirmasSuc;
            this.tecbogRolesIndModFirmas = json.tecbogRolesIndModFirmas;
            this.tecbogRolesIndAutFirmas = json.tecbogRolesIndAutFirmas;
            this.tecbogRolesIndInsertFirmas = json.tecbogRolesIndInsertFirmas;
            this.tecbogRolesPerfilProvisionAtm = json.tecbogRolesPerfilProvisionAtm;
            this.tecbogRolesCodigoEmpleado = json.tecbogRolesCodigoEmpleado;
            this.tecbogRolesCodZona = json.tecbogRolesCodZona;
            this.tecbogRolesTipoAsesor = json.tecbogRolesTipoAsesor;
            this.tecbogRolesAplicaIncentivos = json.tecbogRolesAplicaIncentivos;
            this.tecbogRolesTipoFirmaTeso = json.tecbogRolesTipoFirmaTeso;
            this.tecbogRolesFechaModDato = json.tecbogRolesFechaModDato;
            this.tecbogRolesUsuarioModDat = json.tecbogRolesUsuarioModDat;
            this.tecbogRolesFechaModClave = json.tecbogRolesFechaModClave;
            this.tecbogRolesModalidadAsesor = json.tecbogRolesModalidadAsesor;
            this.tecbogRolesCdtsTesoreria = json.tecbogRolesCdtsTesoreria;
            this.tecbogRolesIndSeguimientoUsuarios = json.tecbogRolesIndSeguimientoUsuarios;
            this.tecbogRolesNoAutorImpresiones = json.tecbogRolesNoAutorImpresiones;
            this.tecbogRolesPerfilPqr = json.tecbogRolesPerfilPqr;
            this.tecbogRolesProfileBaseDatos = json.tecbogRolesProfileBaseDatos;
            this.tecbogRolesRolBaseDatos = json.tecbogRolesRolBaseDatos;
            this.tecbogRolesIndAdministrarUsuarios = json.tecbogRolesIndAdministrarUsuarios;
            this.tecbogRolesIndAdministrarRoles = json.tecbogRolesIndAdministrarRoles;
            this.tecbogRolesIndCrearUsuarios = json.tecbogRolesIndCrearUsuarios;
            this.tecbogRolesIndCrearRoles = json.tecbogRolesIndCrearRoles;
            this.tecbogRolesIndAdministrarAlertas = json.tecbogRolesIndAdministrarAlertas;
            this.tecbogRolesIndTipoSegXTECBOGRolesModulo = json.tecbogRolesIndTipoSegXTECBOGRolesModulo;
            this.tecbogRolesIndGeneraReportesGrales = json.tecbogRolesIndGeneraReportesGrales;
            this.tecbogRolesIndGeneraReportesLog = json.tecbogRolesIndGeneraReportesLog;
            this.tecbogRolesMontoMaxOrdengiroCxp = json.tecbogRolesMontoMaxOrdengiroCxp;
            this.tecbogRolesFiltroReportesCdts = json.tecbogRolesFiltroReportesCdts;
            this.tecbogRolesRolBaseDatosCaja = json.tecbogRolesRolBaseDatosCaja;
            this.tecbogRolesTipoFirmaWfc = json.tecbogRolesTipoFirmaWfc;
            this.tecbogRolesNivelInformes = json.tecbogRolesNivelInformes;
            this.tecbogRolesIndAnalistaAprobacion = json.tecbogRolesIndAnalistaAprobacion;
            this.tecbogRolesIndCambioZona = json.tecbogRolesIndCambioZona;
            this.tecbogRolesDiasPassword = json.tecbogRolesDiasPassword;
            this.tecbogRolesNivel = json.tecbogRolesNivel;
            this.tecbogRolesHorario = json.tecbogRolesHorario;
            this.tecbogRolesIndAdministraNominaAho = json.tecbogRolesIndAdministraNominaAho;
            this.tecbogRolesUsuarioOficinaCxcCxp = json.tecbogRolesUsuarioOficinaCxcCxp;
            this.tecbogRolesAutorAnulaChq = json.tecbogRolesAutorAnulaChq;
            this.tecbogRolesAutReimpChq = json.tecbogRolesAutReimpChq;
            this.tecbogRolesIndCierre = json.tecbogRolesIndCierre;
            this.tecbogRolesIndAnalistaAprobacionActivo = json.tecbogRolesIndAnalistaAprobacionActivo;
            this.tecbogRolesValorAsignacionInicial = json.tecbogRolesValorAsignacionInicial;
            this.tecbogRolesValorAsignacionFinal = json.tecbogRolesValorAsignacionFinal;
        }
    }
}
